"use strict";
let num1 = 10;
let num2 = 5;
let num3;
num3 = num1 + num2;
console.log("Tổng:", num3);
num3 = num1 - num2;
console.log("Hiệu:", num3);
num3 = num1 * num2;
console.log("Tích:", num3);
num3 = num1 / num2;
console.log("Thương:", num3);
console.log("--------------------");
// num1 = "10";
// num2 = true;
// num3 = num1 + num2;
// console.log("Tổng:", num3);
// num3 = num1 - num2;
// console.log("Hiệu:", num3);
// num3 = num1 * num2;
// console.log("Tích:", num3);
// num3 = num1 / num2;
// console.log("Thương:", num3);
//khi thay đổi kiểu dữ liệu chương trình báo bug và khi thực hiện phép tính sẽ cho ra các kết quả không chính xác
